Frontend Signup/login page implementation
bounswe/bounswe2017group10 pull request #135
Opened 2017-10-08 10:47 UTC by bounaykut

2017-10-08 14:04 UTC, yigitozkavci requested changes
When you run `npm start`, it generates the development server and also a linter (ie. code style checker). Do care about these warnings please, they teach us a lot.

![image](https://user-images.githubusercontent.com/7188811/31317496-b4099e32-ac4a-11e7-8e29-273892eb13ae.png)

2017-10-08 14:04 UTC, yigitozkavci commented on Atlas/frontend/src/components/AtlasLogin.js
> +            <Row><h1></h1></Row>
This can't be the way to do it :) You should utilise css margins instead of this.

2017-10-09 10:24 UTC, bounaykut reviewed
I will obey new project structure and care for warnings

2017-10-09 19:57 UTC, yigitozkavci approved these changes

2017-10-09 20:04 UTC, merged