add favorite feature with tests
bounswe/bounswe2017group10 pull request #298
Opened 2017-11-29 14:49 UTC by SaitTalhaNisanci

Fixes #288  .

Changes proposed in this pull request:
- An item can be favorited or 'unfavorited'.
- A user's favorited items can be accessed.
- Each item now shows how many users favorited the item.

To favorite an item send a **POST** request to:
```/user/cultural_heritage_item/id/favorite/```
To 'unfavorite' an item send a **DELETE** request to:
```/user/cultural_heritage_item/id/favorite/```

If two identical requests are received from clients, the others except the first one will return **HTTP_400**.

To see how many times a certain item is favorited, there is **favorited_amount** field in each item. That field is not editible which means that sending **favorited_amount** while creating a new cultural heritage item will not have any effects, in other words that field will be ignored.

To get a user's favorited items send a **GET** request to:
```/user/cultural_heritage_item/favorite/```
Currently it only returns the ids of the items, it should be updated later as the actual items instead of their primary keys.

For each cultural heritage item there is a ```is_favorite``` field which returns true if the current user has that item in their favorite list.

2017-11-29 18:37 UTC, eozd commented
Overall, these changes look quite good. I have tried the functionality you have mentioned on my local server, and things seem fine. When I view the endpoints in Swagger, there seems to be some extra endpoints that you have not mentioned about:

* **GET** ``/user/cultural_heritage_item/favorite``
* **POST** ``/user/cultural_heritage_item/favorite``
* **POST** ``/cultural_heritage_item/{heritage_id}/favorite``

Is this something that should happen, or is this a bug?

2017-11-30 21:17 UTC, eozd submitted a review, later dismissed

2017-12-01 05:26 UTC, yigitozkavci approved these changes

2017-12-01 06:41 UTC, yigitozkavci requested changes
I believe there is a logical mistake here:

- I favorited an item with id 3
- I fetch single cultural heritage, and get `is_favorite` as true, as expected since I **did** favorited this item
- But when I fetch all items, I receive `is_favorite` field of item with id 3 as false, expected to be true.

2017-12-01 13:41 UTC, SaitTalhaNisanci commented
@yigitozkavci  I fixed that bug.

2017-12-02 10:44 UTC, yigitozkavci approved these changes

2017-12-02 10:45 UTC, merged