Update User.java
bounswe/bounswe2017group10 pull request #63
Opened 2017-04-22 14:28 UTC by buseece

Can you take a look at the changes I made, is there any no-needed functions or is there any needed functions to implement?

2017-04-22 14:39 UTC, yigitozkavci requested changes
We should probably use the javadoc standard commenting format, but that's not our priority for now

2017-04-22 14:39 UTC, yigitozkavci commented on API Project/src/main/java/hello/User.java
> +  //private long id?
We need the `id` field, just in case we might want to use a database in the future. Id may not have a setter for now

2017-04-22 14:39 UTC, yigitozkavci commented on API Project/src/main/java/hello/User.java
> +    return "\Username: "+this.userName+ ",Fullname: " + this.getName()
Backslash at the beginning would throw an exception, I didn't understand this part :/

2017-04-23 16:02 UTC, YmirKhang reviewed
Overall it fits our requirements

2017-04-23 20:20 UTC, buseece commented on API Project/src/main/java/hello/User.java
> +    return "\Username: "+this.userName+ ",Fullname: " + this.getName()
It is not a very needed function, but aims to make it easier for us when we want to see user's whole information, when we use retrieve all users informations etc.. But I think in the future using an excel system while retrieving the users' information would be more helpful.

2017-04-23 20:20 UTC, buseece commented on API Project/src/main/java/hello/User.java
> +    return "\Username: "+this.userName+ ",Fullname: " + this.getName()
So for now, I think we don't need this part

2017-04-23 20:21 UTC, buseece commented on API Project/src/main/java/hello/User.java
> +  //private long id?
I also think that we are going to need it, I am going to uncomment it (Y)

2017-04-23 20:31 UTC, merged