Media Item API
bounswe/bounswe2017group10 pull request #84
Opened 2017-04-24 23:39 UTC by egem

Please review the modifications and let me know your comments. 
As far as I tested, it is working correctly.

2017-04-25 11:22 UTC, YmirKhang requested changes
Getters and setters for the string fields?

2017-04-25 11:22 UTC, emir350z commented on API Project/src/main/java/com/bounswe/models/CulturalHeritage.java
> -    }
Nice work but why did you remove all of the getters and setters. We need at least the getters and setters for the string fields.

2017-04-26 08:13 UTC, yigitozkavci commented on API Project/src/main/java/com/bounswe/models/CulturalHeritage.java
> -    }
They were duplicated, apparently @emir350z

2017-04-26 08:14 UTC, yigitozkavci approved these changes
Seems fine to me, nice job indeed :)

2017-04-27 21:11 UTC, YmirKhang approved these changes

2017-04-27 21:11 UTC, merged